#define IDB_GAMEBOARD					101
#define IDR_MENU						102
#define ID_HELP_ABOUT					103
#define ID_FILE_EXIT					104
#define IDB_GAMEBOARD_MASK				105
#define IDB_YELLOWBALL					106
#define IDB_YELLOWBALL_MASK				107
#define IDB_BLUEBALL					108
#define IDB_BLUEBALL_MASK				109
#define IDB_AIPADDLE					110
#define IDB_AIPADDLE_MASK				111
#define IDB_PLAYERPADDLE				112
#define IDB_PLAYERPADDLE_MASK			113
#define IDB_PLAYER2PADDLE				114
#define IDB_PLAYER2PADDLE_MASK			115
#define IDB_TEAMMATEPADDLE				116
#define IDB_TEAMMATEPADDLE_MASK			117
#define IDB_MENUSCREEN					118
#define IDB_MENUSCREEN_MASK				119
#define IDB_GRAYBRICK					120
#define IDB_GRAYBRICK_MASK				121
#define IDB_BROWNBRICK					122
#define IDB_BROWNBRICK_MASK 			123
#define IDB_BLUEBRICK					124
#define IDB_BLUEBRICK_MASK 				125
#define IDB_GAMECOMPLETED_MASK 			126
#define IDB_GAMECOMPLETED				127
#define IDB_GAMEOVER					128
#define IDB_GAMEOVER_MASK				129
#define IDB_WIN							130
#define IDB_WIN_MASK					131
#define IDB_LOSE						132
#define IDB_LOSE_MASK					133
#define IDB_SINGLEPLAYERNORMAL			134
#define IDB_SINGLEPLAYERHIGHLIGHTED		135
#define IDB_SINGLEPLAYERPRESSED			136
#define IDB_TEAMMODENORMAL				137
#define IDB_TEAMMODEHIGHLIGHTED			138
#define IDB_TEAMMODEPRESSED				139
#define IDB_PLAYERVSAINORMAL			140
#define IDB_PLAYERVSAIHIGHLIGHTED		141
#define IDB_PLAYERVSAIPRESSED			142
#define IDB_PLAYERVSPLAYERNORMAL		143
#define IDB_PLAYERVSPLAYERHIGHLIGHTED	144
#define IDB_PLAYERVSPLAYERPRESSED		145
#define IDB_QUITNORMAL					146
#define IDB_QUITHIGHLIGHTED				147
#define IDB_QUITPRESSED					148
#define IDB_BACKTOMENUNORMAL			184
#define IDB_BACKTOMENUHIGHLIGHTED		149
#define IDB_BACKTOMENUPRESSED			150
#define IDB_RESUMENORMAL				151
#define IDB_RESUMEHIGHLIGHTED			152
#define IDB_RESUMEPRESSED				153
#define IDB_BUTTON_MASK 				154
#define IDD_ABOUTBOX					199

#define IDB_BIRD				155
#define IDB_BIRD_MASK 				156
#define IDB_TUBE_UP				157
#define IDB_TUBE_UP_MASK 				158
#define IDB_TUBE_DOWN				159
#define IDB_TUBE_DOWN_MASK 				160
#define IDB_LAYER				164
#define IDB_LAYER_MASK 				165
#define IDB_TUBE_UP_DIAGONAL				166
#define IDB_TUBE_UP_DIAGONAL_MASK 				168
#define IDB_TUBE_DOWN_DIAGONAL				169
#define IDB_TUBE_DOWN_DIAGONAL_MASK 				170
#define IDI_ICON						142

#define IDB_SCORESNORMAL			174
#define IDB_SCORESHIGHLIGHTED		175
#define IDB_SCORESPRESSED			176
#define IDB_BULLET		177
#define IDB_BULLET_MASK			178
#define IDB_DIFFICULTYNORMAL					179
#define IDB_DIFFICULTYHIGHLIGHTED					180
#define IDB_DIFFICULTYPRESSED					181

#define IDB_NORMALNORMAL					192
#define IDB_NORMALHIGHLIGHTED					193
#define IDB_NORMALPRESSED					194
#define IDB_HARDNORMAL					189
#define IDB_HARDHIGHLIGHTED					190
#define IDB_HARDPRESSED					191

#define IDB_EASYNORMAL					186
#define IDB_EASYHIGHLIGHTED					187
#define IDB_EASYPRESSED					188
#define IDB_COIN					195
#define IDB_COIN_MASK				196


#define IDB_TUBE_FACING_LEFT				197
#define IDB_TUBE_FACING_LEFT_MASK 				198

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE		124
#define _APS_NEXT_COMMAND_VALUE			40015
#define _APS_NEXT_CONTROL_VALUE			1007
#define _APS_NEXT_SYMED_VALUE			125
#endif
#endif

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE		122
#define _APS_NEXT_COMMAND_VALUE			40001
#define _APS_NEXT_CONTROL_VALUE			1001
#define _APS_NEXT_SYMED_VALUE			101
#endif
#endif
